ORDER_MIN_USD_VALUE = 10

REDIS_LOCK_TIMEOUT = 10

ORDER_STATUS_PENDING = 'pending'
ORDER_STATUS_COMPLETED = 'completed'

ORDER_STATUSES = [
    (ORDER_STATUS_PENDING, 'Pending'),
    (ORDER_STATUS_COMPLETED, 'Completed'),
]
